# Configuration file for running the server in development mode.

clusterId: default
serverId: default

apiServer:
  port: 8080
  publicHost: localhost
  publicPort: 8080
  publicScheme: http

webServer:
  port: 8081
  publicHost: localhost
  publicPort: 8081
  publicScheme: http

insightsServer:
  port: 8082
  publicHost: localhost
  publicPort: 8082
  publicScheme: http

database:
  enabled: true
  host: localhost
  port: 5432
  name: jinsei_bio_redesign_dev
  user: postgres

redis:
  enabled: false
  host: localhost
  port: 6379

maxRequestSize: 5242880
