clusterId: default
serverId: default

apiServer:
  port: 8080
  publicHost: staging.jinseibio.internal
  publicPort: 8080
  publicScheme: https

webServer:
  port: 8081
  publicHost: staging.jinseibio.internal
  publicPort: 8081
  publicScheme: https

insightsServer:
  port: 8082
  publicHost: staging.jinseibio.internal
  publicPort: 8082
  publicScheme: https

database:
  enabled: true
  host: localhost
  port: 5432
  name: jinsei_bio_redesign_staging
  user: postgres

redis:
  enabled: false
  host: localhost
  port: 6379

maxRequestSize: 5242880
