steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/jinsei-bio-server:latest'
      - '-f'
      - 'jinsei_bio_redesign_server/Dockerfile'
      - '.'
images:
  - 'gcr.io/$PROJECT_ID/jinsei-bio-server:latest'
